version: '3.8'
services:
  client:
    image: kykapple/playground-frontend:0.1
    container_name: client
    ports:
      - "80:80"
    depends_on:
      - server
  server:
    image: kykapple/playground-backend:0.1
    container_name: server
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"